// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamTime.Models;

namespace SteamTime.Migrations
{
    [DbContext(typeof(SteamTimeContext))]
    [Migration("20210806233933_BooleanPlayedLast2Weeks")]
    partial class BooleanPlayedLast2Weeks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SteamTime.Models.SteamGame", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HashImgLogo");

                    b.Property<string>("Name");

                    b.Property<int>("PlayTime");

                    b.Property<bool>("PlayedInLastTwoWeeks");

                    b.Property<string>("SteamId");

                    b.HasKey("AppId");

                    b.ToTable("SteamGame");
                });
#pragma warning restore 612, 618
        }
    }
}
